### PR TITLE
Correct conversion to virion

### PR DESCRIPTION
**Pull request by SOF3**

### CODE REVIEW

**Comment by SOF3** [comment]
I'm not very sure if Poggit handles project type change correctly &mdash; it has never been tested before. If it doesn't work after merging, tell me and I'll reset the project on Poggit.

**Comment by SOF3** [comment]
Please also consider merging https://github.com/SOF3/BossAnnouncement/commit/49cda3dc8b564afbafb7ef760c20227b5e876b1a to BossAnnouncement if you merge this PR to make sure it works.

**Comment by thebigsmileXD** [comment]
People still want to use the plugin as normal, without being forced to head to poggit and use virons. Deletion of files is not wished due to this case.

**Comment by SOF3** [comment]
Agreed. I'm probably pushing virion support too quickly.
As a side note, in case you are concerned, Poggit will still not accept plugins using BossBarAPI in non-virion format. In case you aren't concerned, just ignore this comment, but please don't submit BossBarAPI to Poggit again to save the time of both of us. Thanks.

**Comment by thebigsmileXD** [comment]
Then: Make a fork, upload it. done.

**Comment by SOF3** [comment]
BTW, FYI, I think it should be possible make the same directory dual build as both plugin and virion projects by making two projects at the same path. Never tested it though.

**Comment by thebigsmileXD** [comment]
I saw it at LegendsOfMCPE afair. Might try that.

**Comment by thebigsmileXD** [comment]
> People still want to use the plugin as normal

Actually, we all know virions are better @SOF3

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossBarAPI/commit/4bff0323032635cb285400c74aaffda8bb0113a3 Fixed/Finished

**Pull request closed without merging**
